name: Polls

on:
  issues:
    types: [opened, edited]

jobs:
  polls:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/polls@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
